{-# LANGUAGE ScopedTypeVariables #-}
module Graphos.UseCase.DetectClassificationSpec (spec) where

import qualified Data.Map.Strict as Map
import qualified Data.Text as T
import System.Directory (createDirectoryIfMissing)
import System.IO (writeFile)
import System.IO.Temp (withSystemTempDirectory)
import System.FilePath ((</>))
import Test.Hspec
import Test.QuickCheck (Property, property)

import Graphos.Domain.Types.Pipeline
import Graphos.Domain.Config.Detection (DetectionConfig(..), defaultDetectionConfig, validDetectionConfig)
import Graphos.UseCase.Detect

spec :: Spec
spec = do
  describe "classifyFile: vendored paths" $ do
    it "classifies node_modules as Vendored" $
      classifyFile defaultDetectionConfig (meta "/repo/app/node_modules/foo.js" [] 20) `shouldBe` Vendored
    it "classifies bower_components as Vendored" $
      classifyFile defaultDetectionConfig (meta "/repo/app/bower_components/lib.js" [] 20) `shouldBe` Vendored
    it "classifies vendor as Vendored" $
      classifyFile defaultDetectionConfig (meta "/repo/vendor/lib.js" [] 20) `shouldBe` Vendored
    it "classifies third_party as Vendored" $
      classifyFile defaultDetectionConfig (meta "/repo/third_party/lib.js" [] 20) `shouldBe` Vendored
    it "classifies a deeply nested node_modules path as Vendored regardless of content" $
      classifyFile defaultDetectionConfig (meta "/repo/a/b/c/node_modules/x/y.js" [] 20) `shouldBe` Vendored

  describe "classifyFile: generated headers" $ do
    it "classifies a file whose first line contains 'automatically generated by' as Generated" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// automatically generated by rust-bindgen"] 20) `shouldBe` Generated
    it "classifies a file whose first line contains 'do not edit manually' as Generated" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// do not edit manually"] 20) `shouldBe` Generated
    it "classifies a generated marker on a later line within the window as Generated" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// some normal code", "// do not edit manually"] 20) `shouldBe` Generated
    it "matches generator signatures case-insensitively" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// AUTOMATICALLY GENERATED BY rust-bindgen"] 20) `shouldBe` Generated
    it "does not classify a file as Generated when no signature appears in the leading window" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// fn main() {}"] 20) `shouldBe` Source
    it "uses custom dcGeneratorSignatures" $
      classifyFile (defaultDetectionConfig { dcGeneratorSignatures = ["made by robot"] })
        (meta "/repo/app/main.rs" ["// made by robot"] 20) `shouldBe` Generated

  describe "classifyFile: minified" $ do
    it "classifies a single oversized line beyond the default threshold as Minified" $
      classifyFile defaultDetectionConfig (meta "/repo/app/bundle.js" [T.pack (replicate 6000 'a')] 6000) `shouldBe` Minified
    it "does not classify a multi-line file as Minified when no line exceeds the threshold" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// fn main() {}", "// let x = 1;"] 20) `shouldBe` Source
    it "treats a line exactly at the threshold as Source (strictly greater)" $
      classifyFile defaultDetectionConfig (meta "/repo/app/bundle.js" [T.pack (replicate 5000 'a')] 5000) `shouldBe` Source
    it "respects a custom dcMinifiedLineThreshold" $ do
      let cfg = defaultDetectionConfig { dcMinifiedLineThreshold = 10 }
      classifyFile cfg (meta "/repo/app/bundle.js" ["short"] 5) `shouldBe` Source
      classifyFile cfg (meta "/repo/app/bundle.js" [T.pack (replicate 15 'a')] 15) `shouldBe` Minified

  describe "classifyFile: precedence" $ do
    it "prefers Vendored over Generated when both apply" $
      classifyFile defaultDetectionConfig (meta "/repo/app/node_modules/gen.js" ["// automatically generated by x"] 20) `shouldBe` Vendored
    it "prefers Vendored over Minified when both apply" $
      classifyFile defaultDetectionConfig (meta "/repo/vendor/bundle.js" [T.pack (replicate 6000 'a')] 6000) `shouldBe` Vendored
    it "prefers Generated over Minified when both apply" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["// automatically generated by x"] 6000) `shouldBe` Generated
    it "classifies a plain human-authored file as Source" $
      classifyFile defaultDetectionConfig (meta "/repo/app/main.rs" ["fn main() {", "    println!(\"hi\");", "}"] 20) `shouldBe` Source

  describe "classifyFile: invariants" $ do
    it "always yields one of the four FileClasses" $ property $ \(p :: String) (ls :: [String]) (n :: Int) ->
      let fm' = FileMeta p (map T.pack ls) n
      in classifyFile defaultDetectionConfig fm' `elem` [Source, Generated, Vendored, Minified]

  describe "categorizeFilesWithConfig (integration)" $ do
    it "classifies generated, vendored, minified and source files read from disk" $ do
      let cfg = defaultDetectionConfig
          extMap = Map.empty
          srcLibRs = "src" </> "lib.rs"
          genRs    = "generated.rs"
          vendJs   = "vendor" </> "lib.js"
          thirdJs  = "third_party" </> "lib.js"
          minJs    = "minified.js"
          allNames = [srcLibRs, genRs, vendJs, thirdJs, minJs]
      withSystemTempDirectory "graphos-detect-classification-integration" $ \tmpDir -> do
        createDirectoryIfMissing True (tmpDir </> "src")
        createDirectoryIfMissing True (tmpDir </> "vendor")
        createDirectoryIfMissing True (tmpDir </> "third_party")
        writeFile (tmpDir </> srcLibRs) "fn main() {}\n"
        writeFile (tmpDir </> genRs) "// automatically generated by rust-bindgen\nconst x = 1;\n"
        writeFile (tmpDir </> vendJs) "console.log('vendor')\n"
        writeFile (tmpDir </> thirdJs) "console.log('third party')\n"
        writeFile (tmpDir </> minJs) (replicate 6000 'a')
        let allFiles = map (tmpDir </>) allNames
        (_, byClass) <- categorizeFilesWithConfig allFiles extMap cfg
        Map.lookup Vendored byClass `shouldBe` Just [tmpDir </> vendJs, tmpDir </> thirdJs]
        Map.lookup Generated byClass `shouldBe` Just [tmpDir </> genRs]
        Map.lookup Minified byClass `shouldBe` Just [tmpDir </> minJs]
        Map.lookup Source byClass `shouldBe` Just [tmpDir </> srcLibRs]

meta :: FilePath -> [T.Text] -> Int -> FileMeta
meta p ls n = FileMeta p ls n
