module Graphos.UseCase.ScaffoldSpec where

import Test.Hspec
import Data.List.NonEmpty (NonEmpty(..))
import Control.Monad (forM_)
import qualified Data.Text as T
import Graphos.Domain.Scaffold
import Graphos.UseCase.Scaffold
import Graphos.CLI.Parser (renderCommandReference)

spec :: Spec
spec = do
  describe "selectTargets" $ do
    it "uses explicit list when provided" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = True, dfClaudeDirExists = True }
      selectTargets (Just [Claude, Generic]) facts
        `shouldBe` (Claude :| [Generic])

    it "uses explicit single target" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = False, dfClaudeDirExists = False }
      selectTargets (Just [Opencode]) facts
        `shouldBe` (Opencode :| [])

    it "detects opencode dir" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = True, dfClaudeDirExists = False }
      selectTargets Nothing facts
        `shouldBe` (Opencode :| [])

    it "detects claude dir" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = False, dfClaudeDirExists = True }
      selectTargets Nothing facts
        `shouldBe` (Claude :| [])

    it "detects both dirs" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = True, dfClaudeDirExists = True }
      selectTargets Nothing facts
        `shouldBe` (Opencode :| [Claude])

    it "defaults to all three when nothing detected" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = False, dfClaudeDirExists = False }
      selectTargets Nothing facts
        `shouldBe` (Opencode :| [Claude, Generic])

    it "explicit list overrides detection" $ do
      let facts = DetectionFacts { dfOpencodeDirExists = True, dfClaudeDirExists = True }
      selectTargets (Just [Generic]) facts
        `shouldBe` (Generic :| [])

  describe "planScaffold" $ do
    let ver = "0.1.0.0"
        ref = CommandReference renderCommandReference

    it "produces two files for Opencode target" $ do
      let req = ScaffoldRequest { srTargets = Opencode :| [], srVersion = ver }
          files = planScaffold req ref
      length files `shouldBe` 2
      map sfRelativePath files `shouldBe`
        [ ".opencode/skills/graphos/SKILL.md"
        , ".opencode/agent/graphos-navigator.md"
        ]

    it "produces two files for Claude target" $ do
      let req = ScaffoldRequest { srTargets = Claude :| [], srVersion = ver }
          files = planScaffold req ref
      length files `shouldBe` 2
      map sfRelativePath files `shouldBe`
        [ ".claude/skills/graphos/SKILL.md"
        , ".claude/agents/graphos-navigator.md"
        ]

    it "produces one file for Generic target" $ do
      let req = ScaffoldRequest { srTargets = Generic :| [], srVersion = ver }
          files = planScaffold req ref
      length files `shouldBe` 1
      map sfRelativePath files `shouldBe` [".agents/graphos.md"]

    it "produces five files for all three targets" $ do
      let req = ScaffoldRequest { srTargets = Opencode :| [Claude, Generic], srVersion = ver }
          files = planScaffold req ref
      length files `shouldBe` 5

    it "includes version stamp in every file" $ do
      let req = ScaffoldRequest { srTargets = Opencode :| [Claude, Generic], srVersion = ver }
          files = planScaffold req ref
      forM_ files $ \f ->
        sfContent f `shouldSatisfy` T.isInfixOf ("generated by graphos " <> ver)

    it "includes command reference in skill files" $ do
      let req = ScaffoldRequest { srTargets = Opencode :| [], srVersion = ver }
          files = planScaffold req ref
          skillFile = case files of (f:_) -> f; [] -> error "no files"
      sfContent skillFile `shouldSatisfy` T.isInfixOf "graphos query"

    it "opencode navigator frontmatter restricts tools" $ do
      let req = ScaffoldRequest { srTargets = Opencode :| [], srVersion = ver }
          files = planScaffold req ref
          navFile = files !! 1
      sfContent navFile `shouldSatisfy` T.isInfixOf "graphos *"
      sfContent navFile `shouldSatisfy` T.isInfixOf "edit: false"
      sfContent navFile `shouldSatisfy` T.isInfixOf "write: false"

    it "claude navigator frontmatter restricts tools" $ do
      let req = ScaffoldRequest { srTargets = Claude :| [], srVersion = ver }
          files = planScaffold req ref
          navFile = files !! 1
      sfContent navFile `shouldSatisfy` T.isInfixOf "graphos *"
      sfContent navFile `shouldSatisfy` T.isInfixOf "Read"

    it "navigator files permit graph maintenance" $ do
      let req = ScaffoldRequest { srTargets = Opencode :| [], srVersion = ver }
          files = planScaffold req ref
          navFile = files !! 1
      sfContent navFile `shouldSatisfy` T.isInfixOf "--update"
      sfContent navFile `shouldSatisfy` T.isInfixOf "ingest"