-- | Generated / vendored / minified code detection configuration.
--
-- This is a leaf module: it depends on no other Graphos modules, so it can be
-- imported freely by 'Graphos.Domain.Config', downstream use-cases, and
-- infrastructure without introducing a module cycle.
module Graphos.Domain.Config.Detection
  ( DetectionMode(..)
  , DetectionConfig(..)
  , defaultDetectionConfig
  , validDetectionConfig
  , applyDetectionOverrides
  ) where

import Control.DeepSeq (NFData)
import Data.Maybe (fromMaybe)
import Data.Aeson (ToJSON(..), FromJSON(..), withObject, withText, (.:?))
import Data.Text (Text)
import qualified Data.Text as T
import GHC.Generics (Generic)

-- | How detected (non-'Source') files are handled before extraction.
data DetectionMode
  = Exclude   -- ^ drop detected files entirely (default)
  | Collapse  -- ^ replace each detected file with one node carrying childCount
  | Off       -- ^ classify without excluding or collapsing
  deriving (Eq, Show, Ord, Generic)

instance NFData DetectionMode

instance ToJSON DetectionMode where
  toJSON Exclude  = "exclude"
  toJSON Collapse = "collapse"
  toJSON Off      = "off"

instance FromJSON DetectionMode where
  parseJSON = withText "DetectionMode" $ \t -> case t of
    "exclude"  -> pure Exclude
    "collapse" -> pure Collapse
    "off"      -> pure Off
    _          -> fail $ "Unknown detection mode: " ++ T.unpack t

-- | Tunable parameters for the generated-code detection pass.
data DetectionConfig
  = DetectionConfig
    { dcGeneratorSignatures :: [Text]      -- ^ phrases that mark a file as generated
    , dcVendorSegments      :: [String]     -- ^ vendored directory segment names
    , dcMinifiedLineThreshold :: Int        -- ^ longest allowed line before a file is Minified
    , dcLeadingLines        :: Int          -- ^ header-sniff window (first N lines)
    , dcMode                :: DetectionMode -- ^ exclude / collapse / off
    } deriving (Eq, Show, Generic)

instance NFData DetectionConfig

-- | YAML decoding for the detection configuration. Absent keys fall back to the
-- same values as 'defaultDetectionConfig' so a partial block still yields a
-- valid config instead of failing the whole load.
instance FromJSON DetectionConfig where
  parseJSON = withObject "DetectionConfig" $ \v -> do
    sigs   <- v .:? "generator_signatures" >>= pure . maybe ["automatically generated by", "do not edit manually"] id
    segs   <- v .:? "vendor_segments"        >>= pure . maybe ["node_modules", "bower_components", "vendor", "third_party"] id
    thr    <- v .:? "minified_line_threshold" >>= pure . maybe 5000 id
    lead   <- v .:? "leading_lines"          >>= pure . maybe 40 id
    mode   <- v .:? "mode"                     >>= pure . maybe Exclude id
    pure $ DetectionConfig sigs segs thr lead mode

-- | Default detection configuration: exclude generated/vendored/minified code.
defaultDetectionConfig :: DetectionConfig
defaultDetectionConfig = DetectionConfig
  { dcGeneratorSignatures = ["automatically generated by", "do not edit manually"]
  , dcVendorSegments = ["node_modules", "bower_components", "vendor", "third_party"]
  , dcMinifiedLineThreshold = 5000
  , dcLeadingLines = 40
  , dcMode = Exclude
  }

-- | Validating smart constructor: rejects non-positive thresholds so a
-- mis-configured DetectionConfig can never disable the length guard silently.
validDetectionConfig :: DetectionConfig -> Either String DetectionConfig
validDetectionConfig c
  | dcLeadingLines c < 1 =
      Left $ "dcLeadingLines must be >= 1, got " ++ show (dcLeadingLines c)
  | dcMinifiedLineThreshold c <= 0 =
      Left $ "dcMinifiedLineThreshold must be > 0, got " ++ show (dcMinifiedLineThreshold c)
  | otherwise = Right c

-- | Resolve the effective detection configuration from CLI-derived overrides on
-- top of a base 'DetectionConfig', then validate the result.
--
-- The mode override encodes the --no-detect precedence (the caller resolves
-- that precedence and passes 'Off' when detection is disabled); an explicit
-- minified-line-threshold replaces the base value, otherwise the base value is
-- kept. The result runs through 'validDetectionConfig' so a bad threshold can
-- never disable the length guard silently.
applyDetectionOverrides
  :: DetectionConfig   -- ^ base config from graphos.yaml (or defaults)
  -> DetectionMode     -- ^ effective mode ('Off' disables detection)
  -> Maybe Int         -- ^ minified-line-threshold override (Nothing keeps the base value)
  -> Either String DetectionConfig
applyDetectionOverrides base mode mThreshold =
  validDetectionConfig
    ( base { dcMode = mode
           , dcMinifiedLineThreshold = fromMaybe (dcMinifiedLineThreshold base) mThreshold } )
