apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'service']
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: ['job', 'instance', 'service']
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9099
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
