module Graphos.Domain.ScaffoldSpec where

import Test.Hspec
import qualified Data.Text as T

import Graphos.Domain.Scaffold

spec :: Spec
spec = do
  describe "ScaffoldTarget" $ do
    describe "renderTarget" $ do
      it "renders all targets" $ do
        renderTarget Opencode `shouldBe` "opencode"
        renderTarget Claude   `shouldBe` "claude"
        renderTarget Generic  `shouldBe` "generic"

    describe "parseTarget" $ do
      it "parses valid targets" $ do
        parseTarget "opencode" `shouldBe` Right Opencode
        parseTarget "claude"   `shouldBe` Right Claude
        parseTarget "generic"  `shouldBe` Right Generic

      it "is case-insensitive and strips whitespace" $ do
        parseTarget " Opencode " `shouldBe` Right Opencode
        parseTarget "CLAUDE"     `shouldBe` Right Claude

      it "rejects invalid targets with helpful message" $ do
        case parseTarget "foo" of
          Left msg -> do
            msg `shouldSatisfy` T.isInfixOf "Unknown agent target"
            msg `shouldSatisfy` T.isInfixOf "Valid targets"
          Right _ -> expectationFailure "expected Left for invalid target"

    describe "allTargets" $ do
      it "lists all three targets" $ do
        length allTargets `shouldBe` (3 :: Int)
        allTargets `shouldBe` [Opencode, Claude, Generic]

  describe "substitutePlaceholders" $ do
    it "replaces all placeholders in a template" $ do
      let tpl = "generated by graphos {{VERSION}}\n{{COMMAND_REFERENCE}}\n{{GENERATED_STAMP}}"
          subs = [ ("{{VERSION}}", "0.1.0.0")
                 , ("{{COMMAND_REFERENCE}}", "graphos query")
                 , ("{{GENERATED_STAMP}}", "stamp")
                 ]
      substitutePlaceholders tpl subs
        `shouldBe` "generated by graphos 0.1.0.0\ngraphos query\nstamp"

    it "leaves missing placeholders unchanged" $ do
      let tpl = "hello {{UNKNOWN}} world"
          subs = [("{{VERSION}}", "0.1.0.0")]
      substitutePlaceholders tpl subs `shouldBe` "hello {{UNKNOWN}} world"

    it "handles duplicate placeholders by replacing each occurrence" $ do
      let tpl = "{{VERSION}} and {{VERSION}}"
          subs = [("{{VERSION}}", "0.1.0.0")]
      substitutePlaceholders tpl subs `shouldBe` "0.1.0.0 and 0.1.0.0"

    it "handles empty substitution list" $ do
      let tpl = "no placeholders here"
      substitutePlaceholders tpl [] `shouldBe` tpl

    it "handles empty template" $ do
      substitutePlaceholders "" [("{{VERSION}}", "0.1.0.0")] `shouldBe` ""