{-# LANGUAGE StrictData #-}
module Graphos.UseCase.Scaffold
  ( -- * Detection
    DetectionFacts(..)
  , selectTargets

    -- * Planning
  , planScaffold
  , CommandReference(..)

    -- * Re-export
  , module Graphos.Domain.Scaffold
  ) where

import Data.List.NonEmpty (NonEmpty(..), toList)
import Data.Text (Text)
import qualified Data.Text as T
import Graphos.Domain.Scaffold

data DetectionFacts = DetectionFacts
  { dfOpencodeDirExists :: Bool
  , dfClaudeDirExists   :: Bool
  } deriving (Eq, Show)

selectTargets :: Maybe [ScaffoldTarget] -> DetectionFacts -> NonEmpty ScaffoldTarget
selectTargets Nothing facts =
  let targets = []
        ++ [Opencode | dfOpencodeDirExists facts]
        ++ [Claude   | dfClaudeDirExists facts]
  in case targets of
       [] -> Opencode :| [Claude, Generic]
       (t:ts) -> t :| ts
selectTargets (Just ts) _ =
  case ts of
    [t]    -> t :| []
    (t:ts') -> t :| ts'
    []     -> Opencode :| [Claude, Generic]

newtype CommandReference = CommandReference { unCommandReference :: String }
  deriving (Eq, Show)

planScaffold :: ScaffoldRequest -> CommandReference -> [ScaffoldFile]
planScaffold req ref = concatMap (targetFiles (srVersion req) ref) (toList (srTargets req))

targetFiles :: Text -> CommandReference -> ScaffoldTarget -> [ScaffoldFile]
targetFiles ver ref Opencode =
  [ ScaffoldFile ".opencode/skills/graphos/SKILL.md" (opencodeSkillTemplate ver ref)
  , ScaffoldFile ".opencode/agent/graphos-navigator.md" (opencodeNavigatorTemplate ver)
  ]
targetFiles ver ref Claude =
  [ ScaffoldFile ".claude/skills/graphos/SKILL.md" (claudeSkillTemplate ver ref)
  , ScaffoldFile ".claude/agents/graphos-navigator.md" (claudeNavigatorTemplate ver)
  ]
targetFiles ver ref Generic =
  [ ScaffoldFile ".agents/graphos.md" (genericTemplate ver ref) ]

-- ───────────────────────────────────────────────
-- Template substitution helper
-- ───────────────────────────────────────────────

applyStamp :: String -> String -> String -> String
applyStamp version cmdRef template =
  substitute (substitute (substitute template "{{VERSION}}" version) "{{COMMAND_REFERENCE}}" cmdRef) "{{GENERATED_STAMP}}" ("generated by graphos " ++ version)

substitute :: String -> String -> String -> String
substitute template placeholder value =
  replaceAll placeholder value template

replaceAll :: String -> String -> String -> String
replaceAll _ _ [] = []
replaceAll pat repl s@(c:cs)
  | take (length pat) s == pat = repl ++ replaceAll pat repl (drop (length pat) s)
  | otherwise = c : replaceAll pat repl cs

-- ───────────────────────────────────────────────
-- Opencode skill template
-- ───────────────────────────────────────────────

opencodeSkillTemplate :: Text -> CommandReference -> Text
opencodeSkillTemplate ver (CommandReference ref) = T.pack $ applyStamp (T.unpack ver) ref opencodeSkillProse

opencodeSkillProse :: String
opencodeSkillProse = unlines
  [ "<!-- {{GENERATED_STAMP}} -->"
  , ""
  , "# Graphos Knowledge Graph Skill"
  , ""
  , "You have access to a local knowledge graph built by **graphos** — a tool that turns"
  , "code, docs, and files into a navigable graph of symbols and their relationships."
  , ""
  , "## When to use"
  , ""
  , "- **Prefer `graphos query`** over `grep`/`ripgrep` for finding symbols, understanding"
  , "  relationships, or answering \"where is X used?\""
  , "- Use `graphos path` to find the dependency/relationship path between two symbols"
  , "- Use `graphos explain` to get a detailed breakdown of a node and its neighborhood"
  , "- Use `graphos symbols` to look up an exact symbol by name (fastest for known names)"
  , "- Use `graphos neighbors` to expand around a node with configurable depth"
  , ""
  , "## Decision flow"
  , ""
  , "1. Need to find where a symbol is defined or used? → `graphos query <term>`"
  , "2. Need to understand how two symbols connect? → `graphos path <from> <to>`"
  , "3. Need a detailed view of one symbol? → `graphos explain <node>`"
  , "4. Know the exact name? → `graphos symbols <name>` (faster, exact match)"
  , "5. Want to explore around a node? → `graphos neighbors <id> --depth 2`"
  , ""
  , "## Keeping the graph fresh"
  , ""
  , "- If the graph is stale or missing recent changes: `graphos . --update --no-viz`"
  , "- For a full rebuild: `graphos .` (slower but comprehensive)"
  , "- To add a new file: `graphos ingest <file>`"
  , ""
  , "## Command reference"
  , ""
  , "{{COMMAND_REFERENCE}}"
  , ""
  , "## Rules"
  , ""
  , "- Always prefer the graph over grep for codebase questions"
  , "- Use `--json` output when you need structured data for further processing"
  , "- Use `--update` for incremental refreshes; full builds only when necessary"
  ]

-- ───────────────────────────────────────────────
-- Opencode navigator sub-agent template
-- ───────────────────────────────────────────────

opencodeNavigatorTemplate :: Text -> Text
opencodeNavigatorTemplate ver = T.pack $ applyStamp (T.unpack ver) "" opencodeNavigatorProse

opencodeNavigatorProse :: String
opencodeNavigatorProse = unlines
  [ "---"
  , "name: graphos-navigator"
  , "description: Navigate and maintain the Graphos knowledge graph. Query symbols, paths, and neighborhoods. Refresh the graph with --update or ingest new files."
  , "permissions:"
  , "  bash:"
  , "    allow:"
  , "      - graphos *"
  , "    deny: []"
  , "  edit: false"
  , "  write: false"
  , "---"
  , ""
  , "<!-- {{GENERATED_STAMP}} -->"
  , ""
  , "You are a graph navigator agent powered by **graphos**."
  , ""
  , "## What you can do"
  , ""
  , "- Query the knowledge graph: `graphos query <term>`"
  , "- Find paths between symbols: `graphos path <from> <to>`"
  , "- Explain a node in detail: `graphos explain <node>`"
  , "- Look up exact symbols: `graphos symbols <name>`"
  , "- Explore neighborhoods: `graphos neighbors <id> --depth N`"
  , "- Refresh the graph: `graphos . --update --no-viz`"
  , "- Ingest new files: `graphos ingest <file>`"
  , "- Full rebuild: `graphos .` (use sparingly, prefer `--update`)"
  , ""
  , "## Rules"
  , ""
  , "- You may run any `graphos` command"
  , "- You must **never** edit, write, or modify project source files"
  , "- Prefer `--update` and `--no-viz` for refreshes to keep builds fast"
  , "- Use `--json` when the caller needs structured output"
  , "- Report query verdicts (strong/weak/no-match) back to the caller"
  ]

-- ───────────────────────────────────────────────
-- Claude Code skill template
-- ───────────────────────────────────────────────

claudeSkillTemplate :: Text -> CommandReference -> Text
claudeSkillTemplate ver (CommandReference ref) = T.pack $ applyStamp (T.unpack ver) ref claudeSkillProse

claudeSkillProse :: String
claudeSkillProse = unlines
  [ "<!-- {{GENERATED_STAMP}} -->"
  , ""
  , "# Graphos Knowledge Graph Skill"
  , ""
  , "You have access to a local knowledge graph built by **graphos** — a tool that turns"
  , "code, docs, and files into a navigable graph of symbols and their relationships."
  , ""
  , "## When to use"
  , ""
  , "- **Prefer `graphos query`** over `grep`/`ripgrep` for finding symbols, understanding"
  , "  relationships, or answering \"where is X used?\""
  , "- Use `graphos path` to find the dependency/relationship path between two symbols"
  , "- Use `graphos explain` to get a detailed breakdown of a node and its neighborhood"
  , "- Use `graphos symbols` to look up an exact symbol by name (fastest for known names)"
  , "- Use `graphos neighbors` to expand around a node with configurable depth"
  , ""
  , "## Decision flow"
  , ""
  , "1. Need to find where a symbol is defined or used? → `graphos query <term>`"
  , "2. Need to understand how two symbols connect? → `graphos path <from> <to>`"
  , "3. Need a detailed view of one symbol? → `graphos explain <node>`"
  , "4. Know the exact name? → `graphos symbols <name>` (faster, exact match)"
  , "5. Want to explore around a node? → `graphos neighbors <id> --depth 2`"
  , ""
  , "## Keeping the graph fresh"
  , ""
  , "- If the graph is stale or missing recent changes: `graphos . --update --no-viz`"
  , "- For a full rebuild: `graphos .` (slower but comprehensive)"
  , "- To add a new file: `graphos ingest <file>`"
  , ""
  , "## Command reference"
  , ""
  , "{{COMMAND_REFERENCE}}"
  , ""
  , "## Rules"
  , ""
  , "- Always prefer the graph over grep for codebase questions"
  , "- Use `--json` output when you need structured data for further processing"
  , "- Use `--update` for incremental refreshes; full builds only when necessary"
  ]

-- ───────────────────────────────────────────────
-- Claude Code navigator sub-agent template
-- ───────────────────────────────────────────────

claudeNavigatorTemplate :: Text -> Text
claudeNavigatorTemplate ver = T.pack $ applyStamp (T.unpack ver) "" claudeNavigatorProse

claudeNavigatorProse :: String
claudeNavigatorProse = unlines
  [ "---"
  , "name: graphos-navigator"
  , "description: Navigate and maintain the Graphos knowledge graph. Query symbols, paths, and neighborhoods. Refresh the graph with --update or ingest new files."
  , "tools:"
  , "  - name: Bash"
  , "    allowed_commands:"
  , "      - pattern: 'graphos *'"
  , "  - name: Read"
  , "---"
  , ""
  , "<!-- {{GENERATED_STAMP}} -->"
  , ""
  , "You are a graph navigator agent powered by **graphos**."
  , ""
  , "## What you can do"
  , ""
  , "- Query the knowledge graph: `graphos query <term>`"
  , "- Find paths between symbols: `graphos path <from> <to>`"
  , "- Explain a node in detail: `graphos explain <node>`"
  , "- Look up exact symbols: `graphos symbols <name>`"
  , "- Explore neighborhoods: `graphos neighbors <id> --depth N`"
  , "- Refresh the graph: `graphos . --update --no-viz`"
  , "- Ingest new files: `graphos ingest <file>`"
  , "- Full rebuild: `graphos .` (use sparingly, prefer `--update`)"
  , ""
  , "## Rules"
  , ""
  , "- You may run any `graphos` command"
  , "- You must **never** use Edit, Write, or any tool that modifies project source files"
  , "- Prefer `--update` and `--no-viz` for refreshes to keep builds fast"
  , "- Use `--json` when the caller needs structured output"
  , "- Report query verdicts (strong/weak/no-match) back to the caller"
  ]

-- ───────────────────────────────────────────────
-- Generic .agents/ template
-- ───────────────────────────────────────────────

genericTemplate :: Text -> CommandReference -> Text
genericTemplate ver (CommandReference ref) = T.pack $ applyStamp (T.unpack ver) ref genericProse

genericProse :: String
genericProse = unlines
  [ "---"
  , "name: graphos"
  , "description: Navigate and maintain the Graphos knowledge graph. Query symbols, paths, and neighborhoods. Refresh the graph with --update or ingest new files."
  , "---"
  , ""
  , "<!-- {{GENERATED_STAMP}} -->"
  , ""
  , "# Graphos Knowledge Graph Agent"
  , ""
  , "You have access to a local knowledge graph built by **graphos** — a tool that turns"
  , "code, docs, and files into a navigable graph of symbols and their relationships."
  , ""
  , "## When to use"
  , ""
  , "- **Prefer `graphos query`** over `grep`/`ripgrep` for finding symbols, understanding"
  , "  relationships, or answering \"where is X used?\""
  , "- Use `graphos path` to find the dependency/relationship path between two symbols"
  , "- Use `graphos explain` to get a detailed breakdown of a node and its neighborhood"
  , "- Use `graphos symbols` to look up an exact symbol by name (fastest for known names)"
  , "- Use `graphos neighbors` to expand around a node with configurable depth"
  , ""
  , "## Decision flow"
  , ""
  , "1. Need to find where a symbol is defined or used? → `graphos query <term>`"
  , "2. Need to understand how two symbols connect? → `graphos path <from> <to>`"
  , "3. Need a detailed view of one symbol? → `graphos explain <node>`"
  , "4. Know the exact name? → `graphos symbols <name>` (faster, exact match)"
  , "5. Want to explore around a node? → `graphos neighbors <id> --depth 2`"
  , ""
  , "## Keeping the graph fresh"
  , ""
  , "- If the graph is stale or missing recent changes: `graphos . --update --no-viz`"
  , "- For a full rebuild: `graphos .` (slower but comprehensive)"
  , "- To add a new file: `graphos ingest <file>`"
  , ""
  , "## Command reference"
  , ""
  , "{{COMMAND_REFERENCE}}"
  , ""
  , "## Rules"
  , ""
  , "- Always prefer the graph over grep for codebase questions"
  , "- Use `--json` output when you need structured data for further processing"
  , "- Use `--update` for incremental refreshes; full builds only when necessary"
  , "- Do not modify project source files — this agent is for navigation and graph maintenance only"
  ]