name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: "9.10"
        cabal-version: "3.14"

    - name: Configure
      run: cabal configure --enable-tests --enable-benchmarks --flag dev

    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: cabal build --only-dependencies all

    - name: Build
      run: cabal build all

    - name: Run tests
      run: cabal test all

    - name: Haddock
      run: cabal haddock all
